Repository annoviko/pyclustering, pull requests merged in 2020-10, with the labels that each got.

#612 Import ABC from collections.abc for Python 3 compatibility.
  pyclustering/cluster/generator.py
  pyclustering/core/pyclustering_package.py
Labels: Enhancement

#580 add .gitignore file
  .gitignore
Labels: Proposal

#644 [pr][feature] Elbow parameter kstep.
  CHANGES
  ccore/include/pyclustering/cluster/elbow.hpp
  ccore/include/pyclustering/interface/elbow_interface.h
  ccore/include/pyclustering/parallel/parallel.hpp
  ccore/makefile
  ccore/src/interface/elbow_interface.cpp
  ccore/tst/utest-elbow.cpp
  ccore/tst/utest-elbow.hpp
  ccore/tst/utest-interface-elbow.cpp
  ccore/tst/utest-parallel_for.cpp
  ccore/tst/utest-silhouette_ksearch.cpp
  ccore/tst/utest-spinlock.cpp
  pyclustering/__init__.py
  pyclustering/cluster/clique.py
  pyclustering/cluster/elbow.py
  pyclustering/cluster/tests/elbow_template.py
  pyclustering/cluster/tests/integration/it_elbow.py
  pyclustering/cluster/tests/unit/ut_elbow.py
  pyclustering/cluster/tests/unit/ut_gmeans.py
  pyclustering/core/clique_wrapper.py
  pyclustering/core/elbow_wrapper.py
  pyclustering/samples/definitions.py
  pyclustering/samples/samples/simple/Simple15.answer
  pyclustering/samples/samples/simple/Simple15.data
  setup.py
Labels: Enhancement, Optimization
